# Generated by Django 3.1 on 2020-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='state',
            field=models.CharField(default='lagos', max_length=20),
            preserve_default=False,
        ),
    ]
