# Generated by Django 3.1 on 2020-09-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=2000),
            preserve_default=False,
        ),
    ]
